### ISSUE TITLE
change subcase button back to "previous works"

### ISSUE THREAD

**Issue by sifisifisifi** [joonashak/reclab#172]
subcase on ohi, joten ton etusivun nappulan voi laittaa taas menemään sinne aikasempiin teoksiin! 
eng: See our previous artworks
suom: katso täällä aiempia teoksiamme

tms

**Comment by innaminute** [comment]
EDIT!

Vaihdetaan vasemmanpuoleinen ohjaamaan Cirkon sivuille lipun ostoon. Oikeanpuoleinen ohjaamaan aiempiin teoksiin! Päivitän tämän tiketin kun saadaan Cirkolta linkit!
